issues:
  exclude-rules:
    # CGO Problem
    - path: internal/server/api/auth/auth.go
      linters:
        - typecheck
    - path: test/libsodium_client/main.go
      linters:
        - typecheck
