version: "3.9"  # optional since v1.27.0
services:
  primary:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OES_CONFIG_NAME=config_primary.json
    stdin_open: true
    tty: true
  backup:
    build: .
    ports:
      - "8081:8080"
    environment:
      - OES_CONFIG_NAME=config_backup.json
    stdin_open: true
    tty: true
    depends_on:
      - primary
